spring:
  application:
    name: oauth2Basic
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
      url:    jdbc:h2:file:~/test
      username: sa
      password: 
      driver-class-name: org.h2.Driver
security:
  user:
    password: password
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org.springframework.security: INFO
